APP_NAME := "customer-portal"

# Compile and package the application
build:
    mvn clean package

# Build the application and the Docker image, then push it to the local registry
docker: build
    docker build -t {{APP_NAME}}:latest .
    docker tag {{APP_NAME}}:latest localhost:5005/{{APP_NAME}}:latest
    docker push localhost:5005/{{APP_NAME}}:latest
    docker images | grep "{{APP_NAME}}"

# Build the application and run it with the local Spring profile
run: build
    mvn spring-boot:run -Dspring-boot.run.profiles=local

# Show available Maven dependency, plugin and property updates, and scan the Docker image for CVEs
check-updates:
    mvn versions:display-plugin-updates -Dmaven.version.ignore='(?i).*[.-]?(alpha|beta|RC|M)\d*'
    mvn versions:display-property-updates -Dmaven.version.ignore='(?i).*[.-]?(alpha|beta|RC|M)\d*'
    mvn versions:display-dependency-updates -DprocessDependencyManagement=false -Dmaven.version.ignore='(?i).*[.-]?(alpha|beta|RC|M)\d*'
    docker scout cves {{APP_NAME}}:latest
